### ISSUE TITLE
did you use the latest xxh3?

### ISSUE THREAD

**Issue by hiqsociety** [zeebo/xxh3#3]
did you use the latest xxh3?

**Comment by zeebo** [comment]
I used the latest as of 4 months ago, so it probably needs to be updated again.

**Comment by vtolstov** [comment]
thanks! did you plan to update tis package?

**Comment by zeebo** [comment]
yes, but it's unclear when upstream xxh3 is finished. once that happens i'll put in the effort.

**Comment by gitmko0** [comment]
can put in the effort now? there seems to be a huge improvement to it. i think the latest version is ready

**Comment by templexxx** [comment]
> can put in the effort now? there seems to be a huge improvement to it. i think the latest version is ready

Maybe waiting for the v0.8.0 is a better idea.

XXH3's return values will be officially finalized upon reaching v0.8.0.

**Comment by gitmko0** [comment]
@templexxx ok! definitely need to wait then. thx.

**Comment by gitmko0** [comment]
xxh3 0.8 is out! quick implement it!

**Comment by zeebo** [comment]
upstream has fixed the output, and this package now matches (it is also tagged v0.8.0).
